### ISSUE TITLE
Create NuGet Package

### ISSUE THREAD

**Issue by ChrisMissal** [HeadspringLabs/bulk-writer#1]
- [x] Consider downgrading to 4.5 for wider adoption.
- [ ] Include logo in nuspec
- [ ] Get list of tags from @michaelnero

**Comment by jbogard** [comment]
Done!

**Comment by caioproiete** [comment]
NuGet Package: [BulkWriter](https://www.nuget.org/packages/BulkWriter/) - https://www.nuget.org/packages/BulkWriter/
