### ISSUE TITLE
The meaning of the NotMappedAttribute seems to be reversed

### ISSUE THREAD

**Issue by rmja** [HeadspringLabs/bulk-writer#11]
When writing to the database it seems as if I have to put [NotMapped] on all the properties that I want to map, and not the other way around.

The culprit is [this line](https://github.com/HeadspringLabs/bulk-writer/blob/8c933f40c781bde94e785ae45841b68a9a2d35ed/src/BulkWriter/Internal/TypeExtensions.cs#L19):

```
ShouldMap = pi.GetCustomAttribute<NotMappedAttribute>() != null
```

which I think instead should be:

```
ShouldMap = pi.GetCustomAttribute<NotMappedAttribute>() == null
```

**Comment by Hubert-Rybak** [comment]
Fixed in PR #21
