### ISSUE TITLE
BatchSize and BulkCopyTimeout are not applied to SqlBulkCopy (includes PR)

### ISSUE THREAD

**Issue by jasonyandell** [HeadspringLabs/bulk-writer#18]
Currently, SqlBulkCopy is not modified by the property-injected properties

![options_not_applied](https://user-images.githubusercontent.com/389660/31793178-24be05a4-b4e4-11e7-8269-e550d3309b0a.png)

#17 fixes this

**Comment by jbogard** [comment]
Fixed by #17
