### ISSUE TITLE
Fix build warning for non-CLS-compliant types

### ISSUE THREAD

**Issue by goodmanmd** [HeadspringLabs/bulk-writer#57]
During build, warnings like the following are generated:

> BulkWriter.cs(28,71): warning CS3001: Argument type 'SqlBulkCopyOptions' is not CLS-compliant [C:\Code\bulk-writer\src\BulkWriter\BulkWriter.csproj]

This is actually a problem in the `Microsoft.Data.SqlClient` library that is slated to be fixed in an [upcoming release](https://github.com/dotnet/SqlClient/issues/476).  Incorporate this new library release once it's available.

**Comment by daneSchilling** [comment]
Our only course of action is to wait on the package Microsoft.Data.SqlClient to become CLS compliant. We are going to remove our claim of CLS compliant and could re-assess at a later date.
