### ISSUE TITLE
Add logging facility for ETL pipeline

### ISSUE THREAD

**Issue by goodmanmd** [HeadspringLabs/bulk-writer#60]
Currently we have no visibility for the end user on data flowing through the pipeline.  If a given step fails, the overall pipeline output may be incomplete and it won't be clear why.

Add an extension point so the user can pass in a `Microsoft.Extensions.Logging.ILogger` to log any pipeline errors.

**Comment by ChrisMissal** [comment]
One thing I noticed is that there can be errors inside SqlBulkCopy that don't seem to "bubble" up nicely, which leads to a "stuck" pipeline.

**Comment by goodmanmd** [comment]
@ChrisMissal as in, `SqlBulkCopy` doesn't actually raise an exception?
